name: ci

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  selftest-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev g++ cmake
      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j 4
      - name: Selftest
        run: ./build/jptxt --selftest
)
